from pathlib import Path
p=Path('src/components/Users.tsx')
s=p.read_text()
start=s.index('      // Attempt signup in Supabase Auth')
end=s.index('      setActionAlert({ type: "success", msg: `تم إضافة الموظف الجديد ${fullName} بنجاح وترحيله إلى Supabase Auth!` });', start)
end=s.index('\n', end)+1
new='''      // Create staff account through the privileged Edge Function. This keeps the OWNER\'s\n      // browser session intact and creates an already-confirmed Auth user (no email activation).\n      const { data: sessionData, error: sessionError } = await supabase.auth.getSession();\n      const accessToken = sessionData.session?.access_token;\n      if (sessionError || !accessToken) {\n        setActionAlert({ type: "error", msg: "انتهت جلسة المالك. سجل الدخول مرة أخرى ثم أعد المحاولة." });\n        return;\n      }\n\n      const { data: createResult, error: createError } = await supabase.functions.invoke("admin-create-user", {\n        headers: { Authorization: `Bearer ${accessToken}` },\n        body: {\n          fullName: fullName.trim(),\n          username: username.toLowerCase().trim(),\n          email: cleanEmail,\n          password: passToUse,\n          phone: phone.trim() || null,\n          branch,\n          roleId,\n          permissions: roleId === "OWNER" ? ALL_PERMISSIONS : customPermissions,\n          mustChangePassword\n        }\n      });\n\n      if (createError || !createResult?.success) {\n        const message = createResult?.error || createError?.message || "تعذر إنشاء المستخدم في Supabase.";\n        setActionAlert({ type: "error", msg: message });\n        return;\n      }\n\n      const newUser: AuthUser = {\n        id: createResult.user.id,\n        fullName,\n        name: fullName,\n        username: username.toLowerCase().trim(),\n        email: cleanEmail,\n        phone,\n        branch,\n        roleId,\n        role: roleId === "OWNER" || roleId === "ADMIN" ? "admin" : roleId === "TECHNICIAN" ? "technician" : "receptionist",\n        permissions: roleId === "OWNER" ? ALL_PERMISSIONS : customPermissions,\n        isActive: true,\n        mustChangePassword,\n        createdAt: new Date().toISOString(),\n        updatedAt: new Date().toISOString(),\n        createdBy: currentLoggedUser?.fullName || currentLoggedUser?.name,\n        passwordHash: hashPassword(passToUse),\n        avatarUrl: `https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80`\n      };\n\n      // Local store is only a UI cache; Supabase is authoritative.\n      allUsers.push(newUser);\n      authStore.saveUsers(allUsers);\n      setActionAlert({ type: "success", msg: `تم إضافة الموظف الجديد ${fullName} بنجاح بدون رسالة تفعيل بريد.` });\n'''
s=s[:start]+new+s[end:]
p.write_text(s)
print('patched Users.tsx')
